# Generated by Django 5.0.6 on 2024-07-16 17:16

import apps.reservations.choices.status_choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('CHECKED_IN', 'Checked in'), ('CANCELED', 'Canceled')], default=apps.reservations.choices.status_choices.StatusChoices['PENDING'], max_length=64),
        ),
    ]
