# Generated by Django 5.0.6 on 2024-07-09 10:44

import apps.users.choices.user_choices
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=17, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users_detail',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('LESSOR', 'lessor'), ('RENTER', 'renter')], default=apps.users.choices.user_choices.UserChoices['RENTER'], max_length=20)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.userdetail')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
