# Generated by Django 5.0.6 on 2024-07-14 11:01

import apps.listings.choices.appartment_type_choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(choices=[('NOT_IDENTIFIED', 'Not identified'), ('BADEN_WUERTTEMBERG', 'Baden-Württemberg'), ('BAVARIA', 'Bayern'), ('BERLIN', 'Berlin'), ('BRANDENBURG', 'Brandenburg'), ('BREMEN', 'Bremen'), ('HAMBURG', 'Hamburg'), ('HESSE', 'Hessen'), ('LOWER_SAXONY', 'Niedersachsen'), ('MECKLENBURG_VORPOMMERN', 'Mecklenburg-Vorpommern'), ('NORTH_RHINE_WESTPHALIA', 'Nordrhein-Westfalen'), ('RHINELAND_PALATINATE', 'Rheinland-Pfalz'), ('SAARLAND', 'Saarland'), ('SAXONY', 'Sachsen'), ('SAXONY_ANHALT', 'Sachsen-Anhalt'), ('SCHLESWIG_HOLSTEIN', 'Schleswig-Holstein'), ('THURINGIA', 'Thüringen')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('postal_code', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'addresses',
                'unique_together': {('land', 'city', 'street', 'house_number', 'postal_code')},
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rooms', models.SmallIntegerField()),
                ('apartment_type', models.CharField(choices=apps.listings.choices.appartment_type_choices.ApartmentTypeChoice.choices, default=apps.listings.choices.appartment_type_choices.ApartmentTypeChoice['APARTMENT'], max_length=20)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment', to='listings.address')),
            ],
            options={
                'db_table': 'apartments',
            },
        ),
    ]
